//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar\Animation.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace anim {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAnimationListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class AnimationBaseListener : IAnimationListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.objectInitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectInitValue([NotNull] AnimationParser.ObjectInitValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.objectInitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectInitValue([NotNull] AnimationParser.ObjectInitValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.vectorInitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVectorInitValue([NotNull] AnimationParser.VectorInitValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.vectorInitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVectorInitValue([NotNull] AnimationParser.VectorInitValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.groupInitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupInitValue([NotNull] AnimationParser.GroupInitValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.groupInitValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupInitValue([NotNull] AnimationParser.GroupInitValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.actionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionType([NotNull] AnimationParser.ActionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.actionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionType([NotNull] AnimationParser.ActionTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.objectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectValue([NotNull] AnimationParser.ObjectValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.objectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectValue([NotNull] AnimationParser.ObjectValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.vectorValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVectorValue([NotNull] AnimationParser.VectorValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.vectorValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVectorValue([NotNull] AnimationParser.VectorValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.numberValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberValue([NotNull] AnimationParser.NumberValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.numberValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberValue([NotNull] AnimationParser.NumberValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] AnimationParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] AnimationParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] AnimationParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] AnimationParser.TermContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] AnimationParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] AnimationParser.FactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] AnimationParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] AnimationParser.VariableContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] AnimationParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] AnimationParser.ModuleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] AnimationParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] AnimationParser.CodeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] AnimationParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] AnimationParser.InstructionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] AnimationParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] AnimationParser.BlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.parallel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParallel([NotNull] AnimationParser.ParallelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.parallel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParallel([NotNull] AnimationParser.ParallelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequence([NotNull] AnimationParser.SequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.sequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequence([NotNull] AnimationParser.SequenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] AnimationParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] AnimationParser.CommandContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] AnimationParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] AnimationParser.TypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] AnimationParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] AnimationParser.ArgumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] AnimationParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] AnimationParser.FunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.objectAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectAssign([NotNull] AnimationParser.ObjectAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.objectAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectAssign([NotNull] AnimationParser.ObjectAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.groupAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupAssign([NotNull] AnimationParser.GroupAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.groupAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupAssign([NotNull] AnimationParser.GroupAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.numberAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberAssign([NotNull] AnimationParser.NumberAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.numberAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberAssign([NotNull] AnimationParser.NumberAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.vectorAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVectorAssign([NotNull] AnimationParser.VectorAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.vectorAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVectorAssign([NotNull] AnimationParser.VectorAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.booleanAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanAssign([NotNull] AnimationParser.BooleanAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.booleanAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanAssign([NotNull] AnimationParser.BooleanAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.allValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllValues([NotNull] AnimationParser.AllValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.allValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllValues([NotNull] AnimationParser.AllValuesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.variableAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableAssign([NotNull] AnimationParser.VariableAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.variableAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableAssign([NotNull] AnimationParser.VariableAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.altAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAltAssign([NotNull] AnimationParser.AltAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.altAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAltAssign([NotNull] AnimationParser.AltAssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] AnimationParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] AnimationParser.AssignContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.comparingOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparingOperation([NotNull] AnimationParser.ComparingOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.comparingOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparingOperation([NotNull] AnimationParser.ComparingOperationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.comparing"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparing([NotNull] AnimationParser.ComparingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.comparing"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparing([NotNull] AnimationParser.ComparingContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.altBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAltBoolean([NotNull] AnimationParser.AltBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.altBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAltBoolean([NotNull] AnimationParser.AltBooleanContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.exprBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprBoolean([NotNull] AnimationParser.ExprBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.exprBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprBoolean([NotNull] AnimationParser.ExprBooleanContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.termBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermBoolean([NotNull] AnimationParser.TermBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.termBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermBoolean([NotNull] AnimationParser.TermBooleanContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.factBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactBoolean([NotNull] AnimationParser.FactBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.factBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactBoolean([NotNull] AnimationParser.FactBooleanContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.booleanValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanValue([NotNull] AnimationParser.BooleanValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.booleanValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanValue([NotNull] AnimationParser.BooleanValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] AnimationParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] AnimationParser.ActionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf([NotNull] AnimationParser.IfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf([NotNull] AnimationParser.IfContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse([NotNull] AnimationParser.ElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse([NotNull] AnimationParser.ElseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile([NotNull] AnimationParser.WhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile([NotNull] AnimationParser.WhileContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.argValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgValue([NotNull] AnimationParser.ArgValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.argValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgValue([NotNull] AnimationParser.ArgValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] AnimationParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] AnimationParser.ArgumentsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnimationParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] AnimationParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnimationParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] AnimationParser.CallContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace anim
