//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\krzys\Documents\praca\AnimationLanguage\grammar\Animation.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace anim {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AnimationParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IAnimationVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.objectInitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectInitValue([NotNull] AnimationParser.ObjectInitValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.vectorInitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectorInitValue([NotNull] AnimationParser.VectorInitValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.groupInitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupInitValue([NotNull] AnimationParser.GroupInitValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.actionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionType([NotNull] AnimationParser.ActionTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.objectValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectValue([NotNull] AnimationParser.ObjectValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.vectorValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectorValue([NotNull] AnimationParser.VectorValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.numberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberValue([NotNull] AnimationParser.NumberValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] AnimationParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] AnimationParser.TermContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] AnimationParser.FactorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] AnimationParser.VariableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] AnimationParser.ModuleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode([NotNull] AnimationParser.CodeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] AnimationParser.InstructionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] AnimationParser.BlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.parallel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParallel([NotNull] AnimationParser.ParallelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequence([NotNull] AnimationParser.SequenceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] AnimationParser.CommandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] AnimationParser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.wait"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWait([NotNull] AnimationParser.WaitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] AnimationParser.ArgumentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] AnimationParser.FunctionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.objectAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectAssign([NotNull] AnimationParser.ObjectAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.groupAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupAssign([NotNull] AnimationParser.GroupAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.numberAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberAssign([NotNull] AnimationParser.NumberAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.vectorAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVectorAssign([NotNull] AnimationParser.VectorAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.booleanAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanAssign([NotNull] AnimationParser.BooleanAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.allValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllValues([NotNull] AnimationParser.AllValuesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.variableAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssign([NotNull] AnimationParser.VariableAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.altAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltAssign([NotNull] AnimationParser.AltAssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] AnimationParser.AssignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.comparingOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparingOperation([NotNull] AnimationParser.ComparingOperationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.comparing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparing([NotNull] AnimationParser.ComparingContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.altBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltBoolean([NotNull] AnimationParser.AltBooleanContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.exprBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprBoolean([NotNull] AnimationParser.ExprBooleanContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.termBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermBoolean([NotNull] AnimationParser.TermBooleanContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.factBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactBoolean([NotNull] AnimationParser.FactBooleanContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.booleanValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanValue([NotNull] AnimationParser.BooleanValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] AnimationParser.ActionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] AnimationParser.IfContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse([NotNull] AnimationParser.ElseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] AnimationParser.WhileContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.argValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgValue([NotNull] AnimationParser.ArgValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] AnimationParser.ArgumentsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnimationParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] AnimationParser.CallContext context);
}
} // namespace anim
